# ---------------------------------------------
prometheusBlackboxExporter:
  enabled: true

prometheus-blackbox-exporter:
  fullnameOverride: "prometheus-blackbox-exporter"
  config:
    modules:
      http_2xx_3xx_4xx:
        http:
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          valid_status_codes:
            - 200
            - 301
            - 302
            - 308
            - 401
            - 403
          valid_http_versions:
            - HTTP/1.1
            - HTTP/2.0
          tls_config:
            insecure_skip_verify: true
        prober: http
        timeout: 10s
      tcp_connect:
        prober: tcp
        timeout: 10s
  serviceAccount:
    name: "blackbox-exporter"
  pspEnabled: false
