{{- if and (.Capabilities.APIVersions.Has "cert-manager.io/v1") .Values.cainjector.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    preferredChain: ""
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.name }}
    server: {{ .Values.clusterIssuer.server }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.clusterIssuer.ingressClass }}
{{- end -}}
